name: CI Pipeline

on:
  push:
    branches: [ "dev" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ci-cd-intro-python .
      
      - name: Check web server
        run: |
          docker run -d -p 3000:3000 --name ci-cd-intro-python ci-cd-intro-python
          sleep 5
          curl http://localhost:3000 || exit 1

          docker stop ci-cd-intro-python 2>/dev/null || true
      #- name: Run tests
      #  run: |
      #    docker run ci-cd-intro-python pytest